### ISSUE TITLE
HTTPS response: Forbidden

### ISSUE THREAD

**Issue by zopperl** [GimliGloinsSon/MoneyMoney-bitpanda-Extension#10]
Hi Stefan,

endlich ist die Version 2.4.3 von MoneyMoney nutzbar.
Ich habe danach umgehend deine Extension heruntergeladen und wollte mein Bitpanda-Konto einrichten.

Nach der Eingabe des API Keys, erscheint eine Fehlermeldung:
_23:16:23  Lade Kontenliste ...
          Web Banking Engine: Using user-supplied extension bitpanda.lua version 1.01.
          Protocol version: Web Scraping
          Server address: https://api.bitpanda.com/v1/
          Sending: GET https://api.bitpanda.com/v1/ticker
          Received: {"BTC":{"EUR":"53099.85","USD":"63562.97","CHF":"58638.05","GBP":"46115.19","TRY":"510046.70"},"ETH":
...
...
{"EUR":"73.56","USD":"88.05","CHF":"81.23","GBP":"63.88","TRY":"706.54"}}
          Sending: GET https://api.bitpanda.com/v1/trades?type=buy&page=1&page_size=50
          The server responded with the error message: Forbidden. Retrying...
          Sending: GET https://api.bitpanda.com/v1/trades?type=buy&page=1&page_size=50
23:16:24  HTTPS response: Forbidden_
          _**Der Server Ihrer Bank meldet einen internen Fehler. Bitte versuchen Sie es später noch einmal.**_

Kannst du bitte weiterhelfen.

Danke und Gruß
Christian

**Comment by GimliGloinsSon** [comment]
Hi Christian,

ich habe gerade versucht den Fehler nachzuvollziehen. Wollte dazu die Konten bei mir ebenfalls neu laden.
Habe hierzu die bitpanda.lua von der Seite von MoneyMoney genommen und bei mir den beta-Modus ausgestellt.

Ich konnte den Fehler leider nicht nachvollziehen. Bei mir hat alles funktioniert. Eine Idee, die ich noch habe ist, ob Du beim generieren des API-Keys bei Bitpanda die drei Häckchen für:

- Trading,
- Transaktion und
- Guthaben 

gesetzt hast?

Kannst Du das nochmal prüfen?

<img width="462" alt="Bildschirmfoto 2021-04-16 um 20 24 18" src="https://user-images.githubusercontent.com/77415262/115067929-db63f480-9ef1-11eb-8cb9-07202d166d73.png">

Viele Grüße,
Stefan

**Comment by zopperl** [comment]
Hallo Stefan,

super- vielen Dank für den Tipp.
Mein erster API-Key war nur für "Guthaben" generiert. Nachdem ich einen Key mit alle drei Häckchen "Trading, Transaktion und Guthaben" erstellt habe, funktioniert es jetzt auch bei mir.

Viele Grüße
Christian

**Comment by GimliGloinsSon** [comment]
Hi Christian, 

dann viel Spaß mit der Erweiterung :-)

Viele Grüße,
Stefan
