### ISSUE TITLE
Filter "canceled" Transactions

### ISSUE THREAD

**Issue by sluettmann** [GimliGloinsSon/MoneyMoney-bitpanda-Extension#11]
Hallo Stefan, 
zunächst einmal vielen vielen Dank für die tolle Erweiterung. Die hilft mir sehr!

Ich hätte noch eine kleine Erweiterungsanfrage. Könntest du einbauen, dass abgebrochene Transaktionen z.B. im Fiat Wallet rausgefiltert werden? Diese werden aktuell noch angezeigt und verfälschen somit das Gesamtergebnis. Auch das Löschen des Umsatzes über über MoneyMoney hilft leider nichts, da die Einträge beim nächsten aktualisieren wieder auftauchen.

Vielen herzlichen Dank
 Sven

Folgende Transaktion sehe ich beim Abruf:

```json
{
"type": "fiat_wallet_transaction",
"attributes": {
	"fiat_wallet_id": "some UUID",
	"user_id": "another UUID",
	"fiat_id": "1",
	"amount": "xxx.yyy",
	"fee": "xx.yy",
	"to_eur_rate": "1.00000000",
	"time": {
		"date_iso8601": "2021-01-01T12:00:00+01:00",
		"unix": "1234567890"
	},
	"in_or_out": "incoming",
	"type": "deposit",
	"status": "canceled",
	"confirmation_by": "sms",
	"confirmed": true,
	"payment_option_id": "xx",
	"requires_2fa_approval": true,
	"is_savings": false,
	"last_changed": {
		"date_iso8601": "2021-01-01T12:00:00+01:00",
		"unix": "1234567890"
	},
	"tags": [],
	"public_status": "canceled",
	"is_index": false,
	"is_card": false,
	"is_card_order_charge": false
}
```

**Comment by GimliGloinsSon** [comment]
@sluettmann Hi Sven,
kannst Du Dir mal die aktuelle Version aus dem Branch filter_canceled_transaction
https://github.com/GimliGloinsSon/MoneyMoney-bitpanda-Extension/blob/filter_canceled_transaction/bitpanda.lua 
holen und prüfen, ob dass so für Dich passt?

Schönes Wochenende und viele Grüße,
Stefan

**Comment by sluettmann** [comment]
@GimliGloinsSon Hi Stefan.
herzlichen Dank für das schnelle Update. Ist die Extension im Feature-Branch schon signiert? Wenn ich das richtig sehe ist sie das (verständlicherweise) nicht. Ich habe nämlich die MoneyMoney Version über den App Store gekauft und kann somit keine unsignierten Extensions nutzen.

Viele Grüße
 Sven

**Comment by GimliGloinsSon** [comment]
@sluettmann Hi Sven,
nein, leider ist noch nicht signiert. Das kann ich nur über den Hersteller von MoneyMoney machen lassen. Ich wollte aber vorher wissen ob es funktioniert, da ich selbst nicht so eine Konstellation in meinen Wallets habe.

Ich würde es dann erstmal signieren lassen und gebe Dir Bescheid, wenn ich eine signierte Version habe. Grundsätzlich läuft die Extension, aber ich kann halt nicht testen, ob das mit der Filterung wirklich klappt.

Viele Grüße,
Stefan

**Comment by sluettmann** [comment]
@GimliGloinsSon Hi Stefan,
konnte die Extension jetzt auch ohne Signatur validieren und kann dir bestätigen, dass die Anpassungen von dir funktionieren.

Herzlichen Dank :-)

**Comment by GimliGloinsSon** [comment]
@sluettmann 
Hi Sven,
die signierte Datei ist jetzt auch verfügbar.
Viele Grüße,
Stefan
