### ISSUE TITLE
Support Bitpanda Pro

### ISSUE THREAD

**Issue by chbndrhnns** [GimliGloinsSon/MoneyMoney-bitpanda-Extension#12]
How much effort would it be to support Bitpanda Pro, as well? I tried using a Bitpanda Pro API key and it did not work out of the box for me.

Thanks for the extension!

**Comment by GimliGloinsSon** [comment]
Hi,

Bitpanda Pro has a different and more complex API. I didn't use it for myself so therefore I didn't wrote an extension for Bitpanda Pro.
I think it will take more time to support Pro. Unfortunately I don't have the time to do that and as I mentioned I didn't use Bitpanda Pro.

Regards,
Stefan
