### ISSUE TITLE
Aktien

### ISSUE THREAD

**Issue by jsadbjsadljnsa** [GimliGloinsSon/MoneyMoney-bitpanda-Extension#14]
Hallo Herr Hinze,

ist es möglich, dass Sie noch die Übersicht der Aktien mit abfragen können für die Bitpanda Extension?

Vielen Dank für eine kurze Rückmeldung.

VG Bernd Pellmann

**Comment by GimliGloinsSon** [comment]
Hallo Bernd,

ich bin gerade dabei, das zu entwickeln und zu testen. Wenn Du von MoneyMoney eine Version hast, die Du direkt beim Entwickler gekauft hast, dann kannst Du den aktuellen Entwicklungsstand, den Du hier findest: https://github.com/GimliGloinsSon/MoneyMoney-bitpanda-Extension/tree/process_stock_trades mal ausprobieren. Falls Du Probleme findest, kannst Du mir gerne Bescheid geben.

Es funktioniert leider nicht, wenn Du das Programm über den App Store gekauft hast.

Viele Grüße,
Stefan

**Comment by jsadbjsadljnsa** [comment]
Hallo Stefan,

ich habe das Programm über den App Store gekauft, somit kann ich es leider nicht testen.

VG Bernd

**Comment by jsadbjsadljnsa** [comment]
Hallo Stefan,

gibt es hier schon Infos, ab wann die neue Version in etwa verfügbar sein wird?

VG Bernd

**Comment by GimliGloinsSon** [comment]
Hallo Bernd,

Du kannst die signierte Datei direkt bei MoneyMoney: https://moneymoney-app.com/extensions/
oder hier in GitHub: https://github.com/GimliGloinsSon/MoneyMoney-bitpanda-Extension/blob/master/dist/bitpanda.lua

herunterladen.

Viele Grüße,
Stefan 

PS: Gib Bescheid, wenn es irgendwelche Probleme gibt.

**Comment by jsadbjsadljnsa** [comment]
Hi Stefan,

hat alles geklappt, danke dir für den Support!

VG Bernd
