### ISSUE TITLE
Timeouts, likely in line urlStock = "https://api.bitpanda.com/v2/masterdata"

### ISSUE THREAD

**Issue by Jamie-Jameson** [GimliGloinsSon/MoneyMoney-bitpanda-Extension#18]
Hi,

first: the extension is really excellent and does exactly what I need. Although being software developer myself, I wouldn't be able to create such an extenion without significant research and trial and error. So many thanks for this!

I notice that many times, the script runs into a timeout in the first attempt and retries. The second attempt usually succeds smoothly. I think that the mentioned line is responsible for this. It takes long, around a minute to get all data. It seems to receive a lot of it! In case of a timeout, the server responds with a Gateway timeout.

Am I right in suspecting this line to time out? Is really all data needed? To me it looks as if the price for _all_ stock is fetched. However, usually one only has a few items in the depot, right? Would it probably be possible to only fetch the data for the once being in the depot?

I can also provide more information as needed.

Cheers,
Jamie

**Comment by GimliGloinsSon** [comment]
Hi Jamie,
I catch with this URL the current stock prices for the stocks. Unfortunately the API from doesn't offers another the possibility to get the stock prices. At the other queries I only get the amount of stocks. https://developers.bitpanda.com/platform/#bitpanda-public-api

For crytos bitpanda offers a query to get the prices: https://api.bitpanda.com/v1/ticker but not for the stocks.
If you have a better idea how to get the stock prices?

Ciao,
Gimli

**Comment by GimliGloinsSon** [comment]
btw. I also contact the support of Bitpanda but unfortunately I never got an answer.

**Comment by Jamie-Jameson** [comment]
Hi Gimli,

thanks for the answer. No, I don't have any idea. I never looked into the APIs.
Acutally, I only have cryptos :). So for me, querying these would be perfectly fine.

Would it be possible to configure the plugin via MM UI whether or not stocks are needed or not? Then one could use the ticker API if only crypto is needed.
Our would this lead to a separate BitPanda-CryptoOnly plugin?

Cheers,
Jamie

**Comment by GimliGloinsSon** [comment]
Hi Jamie,
did you buy your version of MM directly from developer or AppStore? Can you switch to try beta versions.
There is a point in the Menu "Preferences"

I have published a test version of the extension under https://github.com/GimliGloinsSon/MoneyMoney-bitpanda-Extension/blob/timeouts-%2318/bitpanda.lua

Perhaps you can try this extension if it solves the timeout problem for you.

I try to check if there are stock wallets and if yes, then I query the masterdata.

Ciao,
Gimli

**Comment by Jamie-Jameson** [comment]
I fear I bought it in the App Store :/.
I looked at your changes on the branch. The idea looks promising.

Can I help testing somehow? Probably not without being able to enable unsigned extensions, right?

**Comment by GimliGloinsSon** [comment]
yes, unfortunately with the version from App Store you can not use unsigned extension. I will let this version sign by the developer of MM and hope it will work. 

I will tell you when I got the signed extension.

**Comment by GimliGloinsSon** [comment]
Hi Jamie,

sorry for not answering a long time. I give the version for signing. 
I will tell you when I got the signed version.

**Comment by GimliGloinsSon** [comment]
Hi @Jamie-Jameson,
I've added a new signed version of bitpanda. I hope it will work for you:

https://github.com/GimliGloinsSon/MoneyMoney-bitpanda-Extension/blob/master/dist/bitpanda.lua
