### ISSUE TITLE
Rohstoffe + ETF

### ISSUE THREAD

**Issue by jsadbjsadljnsa** [GimliGloinsSon/MoneyMoney-bitpanda-Extension#20]
Hallo zusammen,

ist es in Planung, auch in MoneyMoney die Rohstoffe und ETFs abbilden zu können?

Danke für eine kurze Rückmeldung.

VG Bernd

**Comment by jsadbjsadljnsa** [comment]
Hallo, ist hier ein Update geplant?

**Comment by GimliGloinsSon** [comment]
Hallo Bernd,

aktuell nutze ich keine Rohstoffe oder ETFs. Wenn ich Zeit finde werde ich es mir aber mal anschauen.
Ein Frage wäre, kannst Du MoneyMoney als Betaversion (sprich Du hast es nicht über den Appstore gekauft) nutzen, um es testen zu können?

VG,
Stefan

**Comment by jsadbjsadljnsa** [comment]
Gibt es hier ein Update?

**Comment by GimliGloinsSon** [comment]
Leider bin ich zeitlich noch nicht dazugekommen.

**Comment by GimliGloinsSon** [comment]
Hallo Bernd,

Erweiterung ist in Arbeit. Für die light-Version habe ich es bereits eingefügt.
https://github.com/GimliGloinsSon/MoneyMoney-bitpanda-light-Extension

Ich sehe gerade, dass Du MM über den Appstore gekauft hattest. Dann kannst Du es leider noch nicht ausprobieren. Dazu muss ich die Datei beim Hersteller noch signieren lassen.

Aber um Dich auf dem laufendem zu halten, es ist in Arbeit ;-)

Viele Grüße,
Gimli

**Comment by GimliGloinsSon** [comment]
Hallo Bernd @jsadbjsadljnsa ,

die alle signierte Version findest Du hier: https://github.com/GimliGloinsSon/MoneyMoney-bitpanda-Extension/blob/master/dist/bitpanda.lua

Ich hoffe, es passt so.

Viele Grüße,
Gimli

**Comment by jsadbjsadljnsa** [comment]
Hallo Gimli,

vielen Dank dafür. Ich kam leider erst soeben zum Testen.

Ich erhalte die folgende Fehlermeldung: Für diese Bank ist keine Web-Banking-Unterstützung vorhanden.

VG Bernd

**Comment by GimliGloinsSon** [comment]
Hallo Bernd,

an welcher Stelle kommt denn die FM? Wenn ich bspw. bei einem bestehenden Wallet im Kontextmenü "Nach neuen Konten suchen..." auswähle, dann wird mir eine Liste der Konten angezeigt und ich kann die neuen Wallets auswählen.

Auch während der regelmäßigen Datenabrufe gibt es keine Probleme.

Viele Grüße,
Gimli

**Comment by jsadbjsadljnsa** [comment]
Genau bei den beidenAktionen kommt die Meldung. 

- Nach neuen Konten suchen
- Regulärer Kontoabruf

Ich habe die lua-Datei aus dem „dist“ Ordner genommen. Oder war das falsch?

**Comment by GimliGloinsSon** [comment]
Eigentlich sollte es damit funktionieren. Habe die Datei auch gerade probiert und kann den Fehler nicht nachvollziehen.

Alternativ kannst Du Dir Datei auch nochmal direkt bei MM runterladen: https://moneymoney-app.com/extensions/bitpanda.lua

**Comment by GimliGloinsSon** [comment]
wie groß ist die Datei, die Du hier runtergeladen hast?

**Comment by jsadbjsadljnsa** [comment]
Die Version von der MM-Webseite hat funktioniert.

Vielen Dank !!!
