### ISSUE TITLE
Cardano (ADA) Wallet not visible

### ISSUE THREAD

**Issue by mdohnke** [GimliGloinsSon/MoneyMoney-bitpanda-Extension#22]
I have BTC, ETH, ETHW and ADA in my bitpanda account.
The ADA wallet is not visible in MoneyMoney.

Any idea what might be the problem?

**Comment by GimliGloinsSon** [comment]
Hi,

do you have staked the Cardano Coin? Unfornately staked coins will not be send by the Bitpanda API and therefore I have no information to show the wallet.

**Comment by GimliGloinsSon** [comment]
fixed Problem that staked Crypto not shown in wallet list. depending on how many percent are staked, the crypto will be shown with an amount of 0 if 100% are staked.

**Comment by GimliGloinsSon** [comment]
Hi @mdohnke,

I've added the signed file with the fixed version: https://github.com/GimliGloinsSon/MoneyMoney-bitpanda-Extension/blob/master/dist/bitpanda.lua

**Comment by mdohnke** [comment]
Hi @GimliGloinsSon, 
this version shows the ADA wallet. Like you mentioned it shows an amount of 0 since I staked 100% there.
Strange that the API is not sending the value of the coins.
Thanks for the quick adaption and the fix.
