### ISSUE TITLE
MoneyMoney Bitpanda Fehlermeldung bei Einrichtung

### ISSUE THREAD

**Issue by thomaskoertge** [GimliGloinsSon/MoneyMoney-bitpanda-Extension#24]
Guten Tag,
ich nutze die Bitpandaerweiterung für MoneyMoney. Erstmal vielen Dank dafür. Ich musste die Erweiterung einmal neu einrichten und bekomme nun folgende Fehlermeldung:

(bitpanda.lua:566: attempt to concatenate global 'currIndexName' (a nil value))

Ich nutze die Version 1.21 der Erweiterung sowie die Version 2.4.21 (419) von MoneMoney. Können sie mir bei dem Problem helfen?

Grüße

ThomasK

**Comment by GimliGloinsSon** [comment]
Hi Thomas,

ich werde mir das mal anschauen, bin momentan aber zeitlich sehr eingespannt.
Ich hätte aber schonmal zwei Fragen vorab:
1. Hast Du einen anderen Indizes als BCI 5, BCI 10 oder BCI 25 in Deinem Depo?
--> das hilft mir das Depot einzugrenzen

2. Hattest Du Deine Version von MoneyMoney im Appstore gekauft oder direkt beim Hersteller?
--> ich bräuchte ggf. Unterstützung beim Testen. Das geht aber nur mit der Version, die beim Hersteller gekauft wurde.


Vielen Dank,
Stefan

**Comment by thomaskoertge** [comment]
Moin Stefan,danke für deine Rückantwort. Zu deinen Fragen:1. Ja ich habe noch vier weitere BCI Indizes - Infrastructure Leaders - Smart Contract Leaders - DeFi Leaders - Media & Entertainment Leaders2. Ich habe meine Version direkt auf der Homepage von MoneyMoney gekauft. Ich hoffe damit kannst du was anfangen. Gruß ThomasVon meinem iPhone gesendetAm 17.01.2023 um 19:31 schrieb Stefan Hinze ***@***.***>:﻿
Hi Thomas,
ich werde mir das mal anschauen, bin momentan aber zeitlich sehr eingespannt.
Ich hätte aber schonmal zwei Fragen vorab:


Hast Du einen anderen Indizes als BCI 5, BCI 10 oder BCI 25 in Deinem Depo?
--> das hilft mir das Depot einzugrenzen


Hattest Du Deine Version von MoneyMoney im Appstore gekauft oder direkt beim Hersteller?
--> ich bräuchte ggf. Unterstützung beim Testen. Das geht aber nur mit der Version, die beim Hersteller gekauft wurde.


Vielen Dank,
Stefan

**Comment by GimliGloinsSon** [comment]
Hallo Thomas,

ich habe ein gefixte Version erstellt:
https://github.com/GimliGloinsSon/MoneyMoney-bitpanda-Extension/blob/24-moneymoney-bitpanda-fehlermeldung-bei-einrichtung/bitpanda.lua

Kannst Du die Datei bei Dir mal ausprobieren, ob es damit funktioniert?
Du musst hierfür ggf. unter Einstellungen > Erweiterungen bei "Digitale Signatur von Extensions überprüfen" den Haken zum Test mal rausnehmen, da die Datei noch nicht signiert ist.

Vielen Dank und viele Grüße,
Stefan

**Comment by GimliGloinsSon** [comment]
[bitpanda.lua.zip](https://github.com/GimliGloinsSon/MoneyMoney-bitpanda-Extension/files/10493751/bitpanda.lua.zip)

bzw. hier ist die Datei als zip

**Comment by thomaskoertge** [comment]
Moin Stefan,vielen Dank für deine Arbeit. Ich habe die Datei ausprobiert. Alles funktioniert ✌🏻Grüße Von meinem iPhone gesendetAm 24.01.2023 um 21:24 schrieb Stefan Hinze ***@***.***>:﻿
bitpanda.lua.zip
bzw. hier ist die Datei als zip

**Comment by GimliGloinsSon** [comment]
Hallo Thomas,

es gibt jetzt auch eine signierte Version. Die findest Du hier:
https://github.com/GimliGloinsSon/MoneyMoney-bitpanda-Extension/blob/master/dist/bitpanda.lua

oder auch bei MoneyMoney: https://moneymoney-app.com/extensions/

Viele Grüße, 
Stefan

**Comment by thomaskoertge** [comment]
Moin Stefandanke für die Info. Vielen Dank nochmal für die Überarbeitung der Erweiterung. Gruß ThomasVon meinem iPhone gesendetAm 26.01.2023 um 18:48 schrieb Stefan Hinze ***@***.***>:﻿
Hallo Thomas,
es gibt jetzt auch eine signierte Version. Die findest Du hier:
https://github.com/GimliGloinsSon/MoneyMoney-bitpanda-Extension/blob/master/dist/bitpanda.lua
oder auch bei MoneyMoney: https://moneymoney-app.com/extensions/
Viele Grüße,
Stefan
