### ISSUE TITLE
bitpanda api V2 masterdata doesn't work

### ISSUE THREAD

**Issue by GimliGloinsSon** [GimliGloinsSon/MoneyMoney-bitpanda-Extension#26]
Since a few days the api from Bitpanda to get stockprices doesn't work. A new method to get the prices is needed.

**Comment by jsadbjsadljnsa** [comment]
Hallo Stefan, können deshalb auch generell keine Kontostände geladen werden? Nutze ich auch für Metals und Rohstoffe.

**Comment by GimliGloinsSon** [comment]
Habe eine Lösung gefunden. Muss die neue Version jetzt noch signieren lassen.

**Comment by jsadbjsadljnsa** [comment]
Super. Danke schon einmal.

**Comment by Metis77** [comment]
Klappt es bei euch mit v1.22? 
Bei mir leider nicht. 

Beim neu einrichten eines Bitpanda Kontos kommt:

```
          Lade Kontenliste ...
          Web Banking Engine: Using user-supplied extension bitpanda.lua version 1.22.
          Protocol version: Web Scraping
          ...
          Sending: GET https://api.bitpanda.com/v2/masterdata
          The server responded with the error message: Not Found. Retrying...
          Sending: GET https://api.bitpanda.com/v2/masterdata
          HTTPS response: Not Found
          Der Server Ihrer Bank meldet einen internen Fehler. Bitte versuchen Sie es später noch einmal.

````

**Comment by jsadbjsadljnsa** [comment]
Die neue Version muss ja noch signiert werden. Oder ist die neue Version die 1.22? Kann ich heute Abend erst testen.

**Comment by Metis77** [comment]
Ich habe die Signierte Version eben über MoneyMoney runtergeladen.
Diese wird mir in den MoneyMoney Einstellungen und im Fehlerprotokoll als "Version 1.22" angezeigt.
Oder ist 1.22 noch die alte?

**Comment by jsadbjsadljnsa** [comment]
1.3 müsste die neue sein gemäß Changelog.

**Comment by GimliGloinsSon** [comment]
Ich habe gerade die signierte Version 1.3 bekommen und hier hochgeladen:

https://github.com/GimliGloinsSon/MoneyMoney-bitpanda-Extension/raw/master/dist/bitpanda.lua

Auf der Seite von MoneyMoney sollte jetzt auch die aktuelle Version verfügbar sein.

**Comment by Metis77** [comment]
super!
Läuft wie geschmiert!

Nur wo ist jetzt dein Spenden Button? ;)
Baue doch mal einen ein und sag Bescheid.

**Comment by jsadbjsadljnsa** [comment]
Läuft wieder, besten Dank Stefan!!!

Frage, dauert der Abruf bei euch knapp drei Minuten? War in den früheren Versionen ebenfalls schon so. Ist mir nur aufgefallen. :-)

**Comment by Metis77** [comment]
Bei mir geht es jetzt viel schneller als früher. 
Aber dauert immer noch lange.

**Comment by GimliGloinsSon** [comment]
@Metis77 einen Spendenbutton gibt es nicht. Du kannst aber gerne etwas für einen wohltätigen Verein spenden.

Vielen Dank!
