### ISSUE TITLE
Feedback zur Bitpanda MoneyMoney Extension

### ISSUE THREAD

**Issue by fstimm** [GimliGloinsSon/MoneyMoney-bitpanda-Extension#6]
Hi Stefan,

ein lang ersehntes Script wurde endlich entwickelt. Mega Danke dafür :-)

Soweit funktioniert es auch mit MoneyMoney, die Abfrage beim ersten Aufruf, bzw. beim erneuten Aufruf dauert aber eine gefühlte Ewigkeit. Liegt aber auch vllt an der Performance bei Bitpanda. Ich werde es mal weiter beobachten.

Frage zur Übersicht bei den Cryptos. Was genau bedeutet Kaufkurs genau? Beim BEST wird mir 0,08 Euro angezeigt, worauf bezieht sich dieser genau? Ist das der durchnittliche Kaufkurs, für den ich zB BEST bezahlt hab? 

Weitere Frage zum Gewinn in Euro und Prozent: Ist das die Performance Berechnung zwischen dem, was man in Summe in ein Asset investiert und wieviel er aktuell Wert ist? 

Beim aktuellen Kurs, wäre es möglich, das rechts vom Komma 4 anstatts 2 Stellen angezeigt werden?

Noch ein Tip: Schreib bitte auf der Seite mit dem Screenshot dazu, das man den API-Key auch als Passwort in MoneyMoney eingeben muss :-)

Ansonsten ein super gemachtes Script.

Sehe gerade im Script, das dieses auch für ?Aktien? vorbereitet ist, wenn ich es richtig interpretiere. TOP.

Einen Rechtschreibfehler habe ich weiters im Script gefunden.

-- String bankCode: Bankzeitzahl oder BIC des Auftraggebers/Zahlungsempfängers
(Bankzeitzahl) :-)

Danke und Gruss

Freddy

**Comment by GimliGloinsSon** [comment]
Hi Freddy,

erst einmal Danke dafür, dass Dir die Extension gefällt.

Zu Deinen Fragen und Anmerkungen:

>  die Abfrage beim ersten Aufruf, bzw. beim erneuten Aufruf dauert aber eine gefühlte Ewigkeit. Liegt aber auch vllt an der Performance bei Bitpanda. Ich werde es mal weiter beobachten.

Ja, leider ist die API nicht so optimal von Bitpanda. Ich kann hier bspw. nicht explizit auswählen, dass ich bspw. nur Cryptos runterlade die ich auch nur habe, sonder es geht nur alles oder nichts. In diesen Datenmengen muss ich mir dann das passenden raussuchen.

> Frage zur Übersicht bei den Cryptos. Was genau bedeutet Kaufkurs genau? Beim BEST wird mir 0,08 Euro angezeigt, worauf bezieht sich dieser genau? Ist das der durchnittliche Kaufkurs, für den ich zB BEST bezahlt hab?

Genau, ich ermittele aus allen Trades (Käufe und Verkäufe) die Du für das Crypto getätigt hast, den durchschnittlichen Kaufpreis. Das ist leider nicht optimal für die Performance, aber die API liefert leider nicht den Kaufpreis für die Cryptos. Ich nur den aktuellen Kurs und die aktuelle Stückzahl über die API abrufen. Der Kaufpreis muss eben aus allen Trades ermittelt werden. Wenn das irgendwann die Performance zu sehr in die Knie zwingt, dann muss ich dies leider rausnehmen und kann nur die aktuelle Stückzahl und Kurs anzeigen. MoneyMoney speichert dann zumindest täglich die Kursentwicklung ab, aber weiß dann nicht, was man in Summe plus oder minus gemacht hat. 
Bei den BEST berücksichtige ich dann auch noch, falls Du BEST zum Bezahlen der Tradinggebühren mit einsetzt. Das ist im Grunde auch nichts anderes als ein Verkauf von BEST.

> Weitere Frage zum Gewinn in Euro und Prozent: Ist das die Performance Berechnung zwischen dem, was man in Summe in ein Asset investiert und wieviel er aktuell Wert ist?

Genau. Wenn ich den Kaufpreis nicht ermitteln würde, dann würde dies nicht angezeigt werden. Man hat dann aber die Möglichkeit, manuell eine Kaufpreis zu hinterlegen. Dann würden diese Infos wieder angezeigt werden.

> Beim aktuellen Kurs, wäre es möglich, das rechts vom Komma 4 anstatts 2 Stellen angezeigt werden?

Das ist ein Anzeigethema von MoneyMoney. Das kann ich nicht beeinflussen. Ich liefere nur die Daten fürs Programm und da sind mehrere Stellen drin. Ich kann da nur mal beim Entwickler von MoneyMoney nachfragen. 

> Noch ein Tip: Schreib bitte auf der Seite mit dem Screenshot dazu, das man den API-Key auch als Passwort in MoneyMoney eingeben muss :-)

Es kommt bald eine neue Version von MoneyMoney. Da wird dann nur noch nach dem API-Key gefragt. Deshalb steht in der Readme auch schon ab Version >= 2.4.3.
Ich werde hierzu dann auch von meinem Script noch ein passendes Update liefern.

> Sehe gerade im Script, das dieses auch für ?Aktien? vorbereitet ist, wenn ich es richtig interpretiere. TOP

Für Aktien nicht. Aber falls Du bei Bitpanda Indizes kaufst, die werden dann noch mal gesondert dargestellt. Auch Edelmetalle werden separat dargestellt (kann ich aber selbst nicht testen, da ich keine Edelmetalle habe). 

> -- String bankCode: Bankzeitzahl oder BIC des Auftraggebers/Zahlungsempfängers
(Bankzeitzahl) :-)

Tippfehler ist korrigiert, wobei das nur eine Kommentarzeile ist. ;-)

Vielen Dank und viele Grüße,
Stefan

**Comment by fstimm** [comment]
Hi Stefan,

für mich wäre wie du geschrieben hast OK, wenn man in moneymoney nur die aktuelle Stückzahl und Kurs anzeigt bekommt. Mir sind da die Trades usw. nicht unbedingt wichtig. Ich habe in Telegram gelesen, das man wohl auf der Bitpanda Seite mit der neuen Version die Portfolio Performance sehen kann. Aber in Summe funktioniert dein Script TOP.

Gruss Freddy

**Comment by GimliGloinsSon** [comment]
Hi Freddy,

ich werde mal schauen, vielleicht mache ich auch noch mal eine Lightversion von der Extension, von man nur die Kurse und Stückzahl sieht.

Viele Grüße,
Stefan

**Comment by fstimm** [comment]
eine Light-Version wäre für mich auch OK. Ich kann selber zwar nicht programmieren, kann das Thema aber gerne weiterhin unterstützen :-)

**Comment by GimliGloinsSon** [comment]
Kurze Frage, kannst Du auch die Betaversion von MoneyMoney benutzen, sprich hast Du es Dir direkt beim Entwickler geholt und nicht im Apple Appstore?

Dann kann ich Dir den ersten Entwurf der Lightversion zukommen lassen.

**Comment by fstimm** [comment]
ja, hab die beta. kannst es mir gerne schicken. ich teste es dann sofort :-)

**Comment by GimliGloinsSon** [comment]
Supi, ich habe sogar gleich zwei Dateien für Dich. Die bitpanda-light.lua ist die Lightversion, die von allen Wallets einfach nur die aktuellen Bestände abruft, ohne Kaufpreis aus den Trades zu ermitteln bzw. Buchungen für die FIAT-Wallets.

Auch die normale bitpanda.lua habe ich nochmal angepasst und dort an der Performance geschraubt. War eine doofe Idee die Daten für jedes Krypto einzeln abzufragen, anstatt gleich am Anfang alle Daten mit einmal zu holen.

Beide Dateien findest Du im Zip.

Viel Spaß beim ausprobieren.


[bitpanda.zip](https://github.com/GimliGloinsSon/MoneyMoney-bitpanda-Extension/files/5893028/bitpanda.zip)

**Comment by fstimm** [comment]
Hi Stefan,
danke fürs bereitstellen der beiden dateien, ich arbeite ab sofort nur noch mit der light version. die performance ist sagenhaft.
genau das, was ich gewollt habe :-)

bist du eigentlich in den telegram bitpanda gruppen unterwegs? 

gruss freddy

**Comment by GimliGloinsSon** [comment]
Hi Freddy,

nein, in den Telegram Gruppen bin ich nicht unterwegs.

Viele Spaß mit der Lightversion und schönes Wochenende,
Stefan

**Comment by fstimm** [comment]
Hi Stefan,
das light script arbeitet sehr zuverlässig :-)
mal eine frage. ich erstelle in moneymoney einen kategorien-gruppe. darunter erstelle ich jeweils eine kategorie zB Bitpanda minus (summiert sind das alle beträge die von meinem giro-konto zu bitpanda gegangen sind -> funktioniert). 
dann erstelle dort ich eine kategorie mit namen Bitpanda plus (hier sollen die wallets eingerechnet werden, welche aus deinem script kommen). es zeigt mir aber immer "null kategorien importiert" an. weisst was ich meine?
könnte es sein, das meine assets keine umsätze sind? anders kann ich es mir nicht erklären.

gruss Freddy

**Comment by GimliGloinsSon** [comment]
Hi Freddy,
genau, das Assets sind keine Umsätze. Das ist eher wie ein Depotbestand. Das ist in der Light Version auch bei den FIAT-Wallets so. Ich zeige nur den aktuellen Kontostand an.
Eine Idee die ich hätte, lade doch Deine FIAT-Wallets (EUR-Wallet etc.) mit der normalen Version und die anderen Wallets mit der Lightversion. Dann hast Du zumindest für die FIAT-Wallets Umsätze.

Viele Grüße,
Stefan

**Comment by fstimm** [comment]
habe es probiert, klappt auch soweit (hätte ich auch selber drauf kommen können) :-)

führte aber nicht zum ziel. denn da sehe ich nur die summen, die ich investiert hatte, nicht aber den portfolio wert, diese seh ich im konto, bzw. in der kontengruppe. genau diesen wert wollte ich mir als kategorie heran ziehen und es in einer kategorien-gruppe gegenzurechnen. Bsp. ich hab 1000 euro investiert und der wert ist aktuell auf 1500 euro. dann wäre mein ziel, das es mir in der kategorien-gruppen überschrift +50% anzeigt.

aber deine idee mit dem mix von beiden scripten behalte ich mal im hinterkopf, vllt brauch ich es eines tages mal :-)

ich check das thema mal mit dem support.

danke und gruss

freddy
