### ISSUE TITLE
MoneyMoney Version

### ISSUE THREAD

**Issue by diekultmacher** [GimliGloinsSon/MoneyMoney-bitpanda-Extension#9]
Hi, you state that at least version 2.4.3 is required. However, it seems that only 2.4.2 has been released so far. Also the link in your documentation leads only to version 2.4.2.

I have installed the plugin in version 2.4.2. When setting up it asks for username and password (=data from Bitpanda account?). It does not ask for the API key. I then get the following error message:

```
"Could not connect to the server https://api.bitpanda.com/v1/ticker because the server name is not yet in the whitelist of MoneyMoney.

Please contact our support with this error message and we will solve the problem as soon as possible."
```

**Comment by GimliGloinsSon** [comment]
Hi,

2.4.3 is correct. I'm in contact with the developer from MoneyMoney. With the upcoming version of MoneyMoney the server from Bitpanda will be added to the whitelist. And also the in the menu you will be asked for the API-Key.

At the moment the extension only works if you can the beta version on MoneyMoney. That is only possible if you bought the app directly from the developers page and not at Apple App Store. Unfortunately Apple didn't allow beta version.

<img width="402" alt="image" src="https://user-images.githubusercontent.com/77415262/107888597-b103b400-6f0d-11eb-9eea-99415c9895a6.png">

You can activate beta under "Einstellungen".
I think you will also be asked for username and password. Add the API-Key in Username and password you can you type whatever you want.

If cannot use the beta version then we only can cross the fingers that version 2.4.3 will be releases soon.

Regards,
Stefan

**Comment by rmuellerb** [comment]
Hi there, thank you very much for this useful extension!
I recommend to put this information (where to put the API key and how to handle the whitelisting issue) into the landing-page. I struggled with the initial setup before I found the correct combination.
Thanks!
Robin

**Comment by GimliGloinsSon** [comment]
Hi Robin,
Thanks for your feedback. I've added more information to the readme.
Regards,
Stefan
